.Dd May 1, 2016
.Dt SNAPTEL 1
.Os Intel SDI-X
.Sh NAME
.Nm snaptel
.Nd A powerful telemetry framework
.Sh SYNOPSIS
.Nm snaptel
.Op global options
.Ar command
.Op command options
.Sh DESCRIPTION
This document describes
.Nm snaptel, the command line tool for managing snap telemetry framework.
.Pp
The global options are as follows:

.Bl -tag -width "PAGEIN" -compact
.It Ar --api-version, -a version
The snapteld API version
.It Ar --config, -c config_file
Path to the snaptel config file
.It Ar --insecure
Ignore certificate errors when connecting to HTTPS REST URL
.It Ar --password, -p password
Password for REST API authentication
.It Ar --url, -u url
Specify the snapteld REST URL to use (e.g. http://localhost:8181)
.It Ar --help, -h
Show help
.It Ar --version, -v
Show snapteld version
.El

The commands are as follows:

.Bl -tag -width "PAGEIN" -compact
.It Ar agreement
Only when tribe mode is enabled.
.It Ar member
Only when tribe mode is enabled.
.It Ar metric
.It Ar plugin
.It Ar plugin-config
Only when tribe mode is enabled.
.It Ar task
.El
.Sh COMMANDS
.Nm snaptel plugin
.Ar commands:
.Pp
.Bl -tag -width "PAGEIN" -compact
.It Ar load [plugin_path]
load plugin in snapteld
.It Ar unload [plugin_type] [plugin_name] [plugin_version]
unload plugin from snapteld
.It Ar list
list loaded snapteld plugins
.El

.Nm snaptel metric
.Ar commands:
.Pp
.Bl -tag -width "PAGEIN" -compact
.It Ar get [metric]
get details on a specific metric
.It Ar list
list available metrics
.El

.Nm snaptel task
.Ar commands:
.Pp
.Bl -tag -width "PAGEIN" -compact
.It Ar enable [task_id]
enable task
.It Ar export [task_id]
export task
.It Ar list
list loaded tasks
.It Ar remove [task_id]
remove task
.It Ar start [task_id]
start task
.It Ar stop [task_id]
stop task
.It Ar watch [task_id]
watch task
.El

.Sh ENVIRONMENT
.Nm snapteld
supports the following evnironment variables:

.Bl -tag -compact
.It SNAP_URL
See snaptel --url
.It SNAPTEL_CONFIG_PATH
See snaptel --config
.El
.Sh SEE ALSO
.Xr snapteld 8 ,
.Xr snapteld_config 5
